### ISSUE TITLE
Time in teardown fixtures is not correctly frozen

### ISSUE THREAD

**Issue by folkvir** [wimglenn/pytest-freezer#14]
Hello 🖖 A bug occured this 29 February 2024 and we finally discover that ignoring `_pytest.runner` in your `freezegun.configure` yields to not freezing time after yielding in a fixture. 

Here is the test we created to assert it: 

```python
import time
import datetime
import pytest

FROZEN_DATETIME = datetime.datetime(2024, 2, 29, 0, 0, 0, tzinfo=datetime.timezone.utc)


def assert_time():
    assert datetime.datetime.now(datetime.timezone.utc).isoformat() == FROZEN_DATETIME.isoformat()
    assert time.gmtime() == FROZEN_DATETIME.timetuple()


@pytest.fixture
def freeze_time_yield_fixture_1():
    assert_time()
    yield
    assert_time()


@pytest.mark.freeze_time(FROZEN_DATETIME.isoformat())
def test_freezer_fixture_datetime(freeze_time_yield_fixture_1):
    """This test tests that the freeze_time fixture correctly freeze the time after and before yielding in a fixture"""
    assert_time()
```

if you remove `_pytest.runner` in `freezegun.configure(extend_ignore_list=["_pytest.terminal", "_pytest.runner"])` this test should be green ✅ while keeping it will break 💥 

Can you reproduce this?

**Comment by wimglenn** [comment]
I can reproduce it, but I don't agree that this an issue? Why should the time remain frozen in the teardown context of the fixture? That's not where asserts should go.

**Comment by folkvir** [comment]
I agree that's not where assert should go but the time should be frozen for the entire workflow. 
Fixtures can be used for setup and teardown and if the setup is frozen, why teardown is not? 

Another thing; If you comment the assert for `time.gmtime` and you use both ignore options; everything is working correctly. Only `time.gmtime` and `time.localtime` seem to not be frozen. I didn't test other time functions.

**Comment by wimglenn** [comment]
Those `"_pytest.terminal", "_pytest.runner"` are ignored [for a reason](https://github.com/pytest-dev/pytest-freezer/commit/78aad061ca68c5c624d5afb79e0c09865dc3ef84). Without that, the results from `--durations` are bogus:

```
$ pytest --help | grep durations
  --durations=N         Show N slowest setup/test durations (N=0 for all)
  --durations-min=N     Minimal duration in seconds for inclusion in slowest
```

It is strange that `datetime.datetime.now` is fixed but `time.gmtime` is not, during the teardown. That seems like a bug.

**Comment by wimglenn** [comment]
I've just looked in freezegun's code and found the reason for the discrepancy with `datetime.datetime.now` and `time.gmtime`. 

The patched `time.gmtime` function has [a check in it where it checks at runtime whether we're inside the ignore list](https://github.com/spulec/freezegun/blob/1.4.0/freezegun/api.py#L199). In the case of the fixture, we're in the frame of `_pytest.runner` so the `_should_use_real_time()` check returns True.

But `datetime.datetime.now` is a method, and the patch for those works differently, it actually patches the entire `datetime.datetime` type with a new `freezegun.api.FakeDatetime` type. The [`FakeDatetime.now` method has no check in the ignore lists](https://github.com/spulec/freezegun/blob/1.4.0/freezegun/api.py#L385-L392), so it remains frozen.

There's nothing pytest-freezer could do here to make these consistent, we just enable/disable freezegun, so any proposed fix there would have to be reported upstream to [freezegun](https://github.com/spulec/freezegun) itself.

**Comment by folkvir** [comment]
Thank you for the investigation! I'll close the issue. As you said this more-likely a freezgun bug and not a one that could be fixed here 👍
